### ISSUE TITLE
For Windows, ensure that unsafe library function errors are suppressed

### ISSUE THREAD

**Issue by jbmonroe** [bel2125/civetweb#105]
A lot of the LUA code uses "unsafe" C library functions, and VS2012 (and later) emits errors when it encounters them

Doing a WIN32 def test at the beginning of the specific files and following with
#define _CRT_SECURE_NO_WARNINGS 
(with an appropriate undo at the end of the file) will lead to builds with no errors (tons of warnings, but no errors--well, not THOSE errors, anyway).

The files are lvm.c, luac.c, lua.c, lstrlib.c, loslib.c, lobject.c, loadlib.c, liolib.c, lauxlib.c, lsqllite3.c.

I know I'm probably the only human being alive doing a Windows build, but... :)

**Comment by kainjow** [comment]
Better to define it at the project level (see Preprocessor) so it applies to all files and the Lua source doesn't need to be modified.

**Comment by jbmonroe** [comment]
I don't want it for the entire project; all my C++ code needs to use the "safe" versions and I don't want the other functions sneaking in when the code goes to the maintenance coders.

**Comment by kainjow** [comment]
Build Lua/civetweb as a static library then, and apply it there.

**Comment by jbmonroe** [comment]
I'm already having to correct from the POSIX names of functions to the ISO C++ names--at this point I'd be better off doing a fork-and-fix than arguing about how I choose to build the code.  Our coding standards require that the code compile without warnings on level 4, too--don't get me started on the level of effort there.

**Comment by bel2125** [comment]
In the project files in the VS2012 folder, there is a define _CRT_SECURE_NO_DEPRECATE, and according to the link below, I should probably also add _CRT_SECURE_NO_WARNING, since it seems to depend on the compiler which one needs to be used:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/3373dd77-ed73-44a6-a52c-53dfd95099ac/crtsecurenowarnings-vs-crtsecurenodeprecate?forum=vcgeneral

I use one Visual Studio project for all "third party" code:
https://github.com/bel2125/civetweb/blob/master/VS2012/civetweb_lua/civetweb_lua.vcxproj
I will not fix warnings in well tested third party components like Lua, so I would consider even a -w (disable all warnings) as legitimate for such components. Lua is used in a thousand projects without problems, so why change this code.

All other code is in different Visual Studio project files. It does not really matter if you link them statically or dynamically, as long as you use different project files. Every project file may have different preprocessor defines.

I think the _CRT_SECURE define needs to be set for all cross platform code using C standard libraries. These warnings will tell you to use Microsoft specific *_s functions, that do not exist anywhere else.

**Comment by bel2125** [comment]
Another way ... if you have a difficult to get on with source code police ... might be to not build Lua at all but use the pre-built binaries for Windows as third party DLL without source (http://luabinaries.sourceforge.net/download.html). 

Civetweb can work with these DLLs as well - also with standard Debian Lua packages.
It's added in the source code more for convenience during development and testing, and easy set up at all systems even if they don't have standard Lua libraries.

**Comment by jbmonroe** [comment]
Definitely could go that route.  For the prototyping work I'm doing it all
the hard way, but once I get the rest of the code the way I want it, I can
change the way it builds to use those DLLs instead.

**Comment by bel2125** [comment]
As a summary:

  - Changing the Lua source to use Microsoft specific C library replacement functions makes no sense here.
  - Using separate project files with the _CRT_SECURE_NO_DEPRECATE / _CRT_SECURE_NO_WARNING defines avoids these warnings, like in the current project files.
  - In a later step, a CMake system could create the project files.
  - Using pre-compiled binaries may also be an option.


I can not do anything more here.
So, I am going to close this issue now.
