### ISSUE TITLE
mg_set_websocket_handler closed websocket, const mg_connection* ?

### ISSUE THREAD

**Issue by deltaluca** [bel2125/civetweb#109]
Previously we would set a ``connection_close`` callback which gets a **non-const** ``mg_connection*`` from which we can get the ``mg_request_info`` and ultimately the per-connection user data to be cleaned up,

however the new ``mg_set_websocket_handler`` closed websocket callback only gets a **const** ``mg_connection*`` so how are we supposed to clean up that per-connection user data now?

Is this just an oversight?

**Comment by bel2125** [comment]
I had a couple of problems with the const vs. not const `mg_connection *` parameters when adding `mg_set_websocket_handler`, but I thought I cleaned them in the end. Maybe there is still a problem.
I thought about removing all the const, since the undefined `struct mg_connection *` is just a handle in the interface anyway.
Finally I used `const` in cases you should not write to the connection.

`mg_get_user_data` should take a const input (https://github.com/bel2125/civetweb/blob/master/include/civetweb.h#L327)
`mg_get_request_info` as well (https://github.com/bel2125/civetweb/blob/master/include/civetweb.h#L392)
`mg_cry` needs to be checked, but probably also needs a const (https://github.com/bel2125/civetweb/blob/master/include/civetweb.h#L639)

This should work for your case. 
But if this `const` topic becomes too complicated and causes too much incompatibilities, I might indeed just remove all the `const` qualifiers and replace it by a comment what methods can be called from which callbacks.

**Comment by bel2125** [comment]
I hope that I finally managed to clean up all `const` vs *not const* issues.
If you still see some, please tell me.

@deltaluca: Please compile your code again, and tell me if it works now in your situation (in a couple of days).

**Comment by bel2125** [comment]
The bug can not be reproduced by me, and there is no reply that it still exists.
It seems the fixes from three weeks ago work for this issue.
