### ISSUE TITLE
Crash when handler does not process a request

### ISSUE THREAD

**Issue by mwegithub** [bel2125/civetweb#122]
Platform Windows, Visual Studio 2012. I use the most recent version of civetweb.

In the **callback_handler** function (civetweb.c), when user-defined callback_handler returns false, the function sets the **callback_handler** pointer to NULL and then jumps to the label auth_check.
After performing some tests, it tries to call the callback handler again via the now NULL function pointer. This causes a crash.

There are comments in the source about how to handle the situation when a user-defined callback returns false, and this seems to be work in progress. I'm new to civetweb and so I feel unable to provide suggestions about how to best solve this. But a crash should be avoided, e.g. by just checking the function pointer for NULL in line 6775 and sending a 405 error code to the browser or something.

**Comment by bel2125** [comment]
Yes, this situation is not fixed yet.
The previous code (before I rewrite the entire request handling method) did look for a file with this name, when a callback was registered but refused to handle the request. I never understood the use case of registering a callback, and then not handling the request. A fallback could be a 404 reply or just closing the connection without any reply - but why serve a file with the same name as the callback?

Since I was not sure if this is a meaningful use case, I did not really test it, but of course it should not crash.
I changed the implementation for this situation.

Still I would be interested in what could be the reason for registering a callback for a certain URI and then not sending a reply there?

**Comment by mwegithub** [comment]
>Still I would be interested in what could be the reason for registering a callback
> for a certain URI and >then not sending a reply there?

This was done accidentally. My callback ran into an error condition and just returned false instead of creating a proper error response and returning true.

The documentation about if and when a callback should return false is a bit sparse/confusing (I refer here to line 83 in civetweb.h). My callbacks now never return false and always return a valid HTML / JSON response with a detailed error message.

But I think that when a user callback returns false, civetweb should not try to be 'smart' (as you pointed out already in your reply) and just handle the situation by sending a 405 to the browser or closing the connection.

Thank you for maintaining this project and for taking care for the occasional bug. I have to say that so far civetweb worked like a charm and proved to be very robust and fast. Excellent!
