### ISSUE TITLE
POST requests to LSP returns Error 405: Method Not Allowed

### ISSUE THREAD

**Issue by shawnye** [bel2125/civetweb#135]
Lua server page:

<pre>
&lt;? mg.write("HTTP/1.1 200 OK") ?&gt;
&lt;? mg.write("Content-Type: text/html") ?&gt;

&lt;!doctype html&gt;
&lt;html&gt;
 &lt;head&gt;
  &lt;meta charset="UTF-8"&gt;
 &lt;/head&gt;
 &lt;body&gt;
    &lt;form action="test_post.lp" method="post" &gt;
       &lt;input type="text" name="name" &gt;
      &lt;input type="submit" name="ok" value="submit"&gt;
   &lt;/form&gt;
 &lt;/body&gt;
&lt;/html&gt;
</pre>

error occurred when submit to `test_post.lp`:

Error 405: Method Not Allowed
POST method not allowed

I change method="GET", it is OK,  I heard apache or nginx does not allow posting to static html, but `test_post.lp` is not static html.

By the way, I really do NOT want show parameters in URL.

**Comment by bel2125** [comment]
Did you try to post to `test_post.lua` instead of `test_post.lp`.
I always considered `*.lp` more like server side includes (`*.shtml`), 
while `*.lua` is a full script (like CGI).

**Comment by shawnye** [comment]
ok, I just think *.lp as *.jsp , *.lua as java servlet at first glance.

**Comment by bel2125** [comment]
Are you building the server from the source on your own?

The code relevant for this should be here (line numbers are subject to change):
https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L3642

This code is in the function `interpret_uri` and looks like this:

			if (0
    #if !defined(NO_CGI)
			    ||
			    match_prefix(conn->ctx->config[CGI_EXTENSIONS],
			                 strlen(conn->ctx->config[CGI_EXTENSIONS]),
			                 filename) > 0
    #endif
    #if defined(USE_LUA)
			    ||
			    match_prefix(conn->ctx->config[LUA_SCRIPT_EXTENSIONS],
			                 strlen(conn->ctx->config[LUA_SCRIPT_EXTENSIONS]),
			                 filename) > 0
    #endif
			    ) {
                      /* ... */
                      *is_script_ressource = !*is_put_or_delete_request;



If you add the same for `match_prefix` condition for `LUA_SERVER_PAGE_EXTENSIONS`, the server considers `*.lsp` as dynamic resource just like `*.lua` and `*.cgi`. 
If you build your server with these additional lines, it will allow `test_post.lsp` to handle POST methods.

It does not yet allow handling sub-resources, i.e., URLs like "http://myserver.com/test_post.lsp/subpath/subres.xyz", which would be possible for `*.lua` and `*.cgi`. If you want to use sub-resources as well, you need to add the same code a few lines below. There is a very similar `if` block (commented `/* Support PATH_INFO for CGI scripts. */`) that misses the same `match_prefix` condition.

I think with these modifications you can reach the behavior you want.


So, the remaining question is: ***Should this be the default?***
I tended to a ***no***, since I thought `*.lsp` is more like SSI than JSP.
Finally there are a lot more differences between `*.lsp` and a standard `*.jsp`. Fully featured JSP interpreters are rather heavy software - trying to recreate all JSP features in Lua is out of scope here.

**Comment by shawnye** [comment]
Thank you for your help! 

Of couse , Recreating all JSP features makes `civetweb` too heavy, which is not what I want. I just want to create about 20% JSP features that used at most time. I would try to implement it with lua, as I am not good at C programming.

**Comment by bel2125** [comment]
Do you have an idea what the most used 20% of the features are? There isn't something like "JSP minimal" standard, right?

**Comment by shawnye** [comment]
Yeah, it is. this topic is out of scope here, so I would like close this issue.
Please see my new issues 138 and 139 and give some suggestion :)
