### ISSUE TITLE
Compilation Error in  main.c(1181): error C2143, followed by a lot of errors

### ISSUE THREAD

**Issue by shawnye** [bel2125/civetweb#138]
Compiled with VS2010, nothing changed except making `civetweb.sln` acknowledged by VS2010

2>  main.c
2>..\..\src\main.c(1181): error C2143: 语法错误 : 缺少“;”(在“&lt;class-head&gt;”的前面) // Syntax error, need ";" before “&lt;class-head&gt;”
2>..\..\src\main.c(1183): error C2275: “WORD”: 将此类型用作表达式非法 // invalid expression:“WORD”

This compilation error may caused by this commit:
https://github.com/bel2125/civetweb/commit/c21748054f069180476c95fadd23fe3ae395fadc

**Comment by bel2125** [comment]
Probably again a problem caused by variable declarations that are not on top of the function, which is possible in gcc since >10 years but in MSVC only since 2013 (http://stackoverflow.com/questions/13308944/how-to-simulate-c99-in-visual-studio-for-variables-declaration)

I will take care of this.

@mattyclarkson: Could we add a travis check for gcc/clang, to test if it the code compiles with c89 as well as c99?

**Comment by shawnye** [comment]
Compilation is OK, close this issue.
