### ISSUE TITLE
mg.redirect(uri)  error: attempt to call field 'redirect' (a nil value)

### ISSUE THREAD

**Issue by shawnye** [bel2125/civetweb#145]
build with lua 5.2.4

index.lua only one line:
 
`mg.redirect("lua/prepare_login.lua")`

E:\Git\SPIM\www/index.lua:1: attempt to call field 'redirect' (a nil value)
stack traceback:
	[string "mg.write(debug.traceback(), '\n')"]:1: in main chunk
	[C]: in function 'redirect'
	E:\Git\SPIM\www/index.lua:1: in main chunk

**Comment by bel2125** [comment]
Did you do your own build?
Did you have a look at `page.lp` and `page.lua`?

**Comment by bel2125** [comment]
I just checked the code:
mg.redirect is available for *.lp only, not for *.lua
I remember, when I made the *.lua pages, I considered a redirect as not required, I just did not document it properly.

In a *.lua file, you will not need a `mg.redirect`, since you can just do a `dofile("lua/prepare_login.lua")`

**Comment by shawnye** [comment]
It works,thank you!

**Comment by shawnye** [comment]
dofile("lua/prepare_login.lua") has a problem:
how do I append parameters?
if using some like `redirect`, I can `mg.redirect("lua/prepare_login.lua?defaultUser=guest")` 

with lua , how can I do that?
Thank you!

**Comment by bel2125** [comment]
`dofile` shares the Lua environment with the original script.
This means, all variables are available set by the first script are available in the second one as well. In a simplified way, you can consider `dofile` as if you would put the required code directly into the first file. More details on `dofile` can be found here http://www.lua.org/pil/8.html

**Comment by bel2125** [comment]
You may also consider to write "prepare_login" as a function in a library written in Lua, and including this library with `require` from your original page. See http://www.lua.org/pil/8.1.html

If you want to redirect the user, you can also use a 303 response, either in *.lp or in *.lua.

LUA (full script):

    require '"whatever.lua"
    loc = "back_to_login.html"
    id = mg.get_cookie(mg.request_info.http_headers.Cookie, "id")
    if (is_valid_id(id)) then loc = "good_page.html" end

    mg.write("HTTP/1.1 303 See Other\r\n")
    mg.write("Connection: close\r\n")
    mg.write("Cache-Control: max-age=0, must-revalidate\r\n")
    mg.write("Location: " .. loc .. "\r\n\r\n")

LP (plain text encoded with Windows line endings):

    HTTP/1.1 303 See Other
    Connection: close
    Cache-Control: max-age=0, must-revalidate
    <? loc = "back_to_login.html"
        id = mg.get_cookie(mg.request_info.http_headers.Cookie, "id")
        if (is_valid_id(id)) then loc = "good_page.html" end
        mg.write("Location: " .. loc)
    ?>
    
    * no content *

I do Login handling like this (in Lua). Login handling can be done by adding a few lines to the every page.

    require 'myLoginHelper.lua'
    loged_in_user = get_logged_in_user_data()
    if not loged_in_user then
        redirect_to_login_page()
        return
    end

    ... here the Lua code for the actual content ... the code can assume the user is logged in

When using lua_preload_files with the proper content, you can do most of these things there, so they are executed for every page.

So I think there is no need for a mg.redirect command, since you have much better opportunities in full Lua scripts.

Any further questions regarding including code from other files?

I can also recommend reading the "Programming in Lua" book (http://www.lua.org/pil/). Currently the third edition (for Lua 5.2) would fit best. The first version (for Lua 5.0) is online (http://www.lua.org/pil/contents.html#8) and still mostly valid for Lua version 5.2, however there are some differences between Lua 5.0 and 5.2.

**Comment by shawnye** [comment]
Thank you!

It works with your `LUA (full script)` example !

For those who not so familiar with HTTP protocol (yes, I am one of them), they may hope there is  tools for it out of box...

**Comment by bel2125** [comment]
> For those who are not so familiar with HTTP protocol (yes, I am one of them), they may hope there is tools for it out of box...

CivetWeb itself should stay rather minimal - the very core is just one C file.
I don't want to add a lot of convenience code there, but I see the demand for a higher level API.
I am thinking about a second project with all these functions - or maybe an additional directory.

**Comment by bel2125** [comment]
Anything else I can do here on the short term?
I agree there is a lack of detailed documentation and also a library with a higher level API will be useful, but I would not do these things with this issue.

**Comment by bel2125** [comment]
No further problems and questions here at the moment, so let's close the topic.
