### ISSUE TITLE
ETag needs to take creation time into account

### ISSUE THREAD

**Issue by PhilLab** [bel2125/civetweb#156]
Similar to https://github.com/bel2125/civetweb/pull/149 we have to deal with the creation time of windows files being newer than the last modified time when constructing the ETag in the function [construct_etag](https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L5315)

**Comment by bel2125** [comment]
Since the `last_modified` member variable is filled with the maximum of either modification date or the creation date, this should already work for all functions using the `last_modified` variable, including `construct_etag`:

https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L2429

Or, did you observe a different behavior?

**Comment by PhilLab** [comment]
ah, well - I missed the aspect that msg_stat is called beforehand
