### ISSUE TITLE
online lua repl

### ISSUE THREAD

**Issue by alisabri** [bel2125/civetweb#160]
Hi,
Thanks for sharing Civetweb. I used Civetweb (modified a bit for LuaJIT) in an online Lua REPL, tide (https://github.com/bitRadio/tide)

Regards,
Ali Sabri

**Comment by bel2125** [comment]
Thank you for the link. You did not get a reply from me yet, not because I am not interested, but because I did not yet manage to test it.
When trying to build it, I got stuck at `#include <lua.h> not found` (ubuntu 15.04), and did not yet look how to solve this best without side effects to other projects. I will have a look during the weekend.

**Comment by alisabri** [comment]
Hi,
Tide requires LuaJIT (which means Lua 5.1 header files and libluajit-5.1) so installing LuaJIT, Lua5.1 (for header files and for Luarock) and changing LUAJIT_INC_DIR and LUAJIT_LIB_DIR paremeters in src/Makefile appropriately (in case Make could not find them) would be enough.

Regards

**Comment by bel2125** [comment]
OK. I had to install Lua 5.1 (just had 5.2).
The `$(shell dirname $(shell which luajit))/..` probably does not work for Debian/Ubuntu, since `which luajit` is /usr/bin/luajit, thus 'dirname' is /usr/bin, the extra `/..` is /usr, so the directories would be /usr/lib and /usr/include. But the Lua headers are installed in '/usr/include/lua5.2/lua.h' and 
'/usr/include/lua5.1/lua.h'.
Also I had to install "libluajit-5.1-2", not "luajit". Then the library path should be '/usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2'.

So I tried
```
LUAJIT_BASE_DIR = not used anymore
LUAJIT_INC_DIR = /usr/include/lua5.1/
LUAJIT_LIB_DIR = /usr/lib/x86_64-linux-gnu/
```

But this still does not work:
`/usr/bin/ld: cannot find -lluajit-5.1`
Maybe because of the extra .2 after the SO, which is actually a link to ...so.2.0.3
```
$ ls -l /usr/lib/x86_64-linux-gnu/libluajit-5.1*
lrwxrwxrwx 1 root root     22 Apr 26  2014 /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2 -> libluajit-5.1.so.2.0.3
-rw-r--r-- 1 root root 453928 Apr 26  2014 /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2.0.3
```

Using 
```
sudo ln -s /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2 /usr/lib/x86_64-linux-gnu/libluajit-5.1.so
```
helps, but I guess this should not be the standard way to build.

**Comment by bel2125** [comment]
After this, I copied the configuration file like in the "Installing" manual section.
Then I start the server and open http://localhost:8080/ in the browser. This automatically redirects to an almost empty window at http://localhost:8081/, which only shows a title (Online Lua/Torch7 repl), and a footer with "about", "source code" and "help".
I just can not find the `th>` shell in the manual and the help.

**Comment by bel2125** [comment]
Ah. I found it by accident: If I use the "back" button of the browser from the help screen, I get to the `th>` input prompt.

'.ls' like in the help does not work
```
orch7 Scientific computing for Lua
./lua/wsserver.lua:116: module 'torch' not found:
	no field package.preload['torch']
	no file './torch.lua'
	no file '/usr/share/luajit-2.0.3/torch.lua'
	no file '/usr/local/share/lua/5.1/torch.lua'
	no file '/usr/local/share/lua/5.1/torch/init.lua'
	no file '/usr/share/lua/5.1/torch.lua'
	no file '/usr/share/lua/5.1/torch/init.lua'
	no file './torch.so'
	no file '/usr/local/lib/lua/5.1/torch.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/torch.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	./lua/wsserver.lua:116: in function <./lua/wsserver.lua:113>
	[C]: in function 'xpcall'
	./lua/wsserver.lua:164: in function <./lua/wsserver.lua:163>
th> .ls
```

**Comment by bel2125** [comment]
.ls
print(23+43)

After some time, I get this popup
```
The program is taking too long to finish. Do you want to stop it?
[Abort] [Ok]
```
Where "Abort" means do not abort the program and "Ok" means abort the program.

I used FireFox 38 for my tests.

I think I have to read the help first before spamming you with messages here.

**Comment by alisabri** [comment]
Hi,
Since you have not installed torch, all you have to do set *torch = false* in .luarc.lua configuration file and restart server.

I should give more detail in README, it is my fault. 
Normally, after opening browser there should not be an empty page (unless there is an error). You can check errors from "error.log" in tide directory

Regards
