### ISSUE TITLE
How to set http return code?

### ISSUE THREAD

**Issue by guanglost** [bel2125/civetweb#178]
when I embedding civetweb with "mg_callbacks" and set the callbacks: "begin_request" and "log_access"，how can I set "http_status" in "struct mg_connection" for loging out?

**Comment by bel2125** [comment]
Just to make clear what you need:
Do you mean `conn->status_code` ?
What do you see in your log files and what do you want to see?

**Comment by guanglost** [comment]
conn->status_code yes!

In the function： static void log_access(civetweb.c),
mg_snprintf(conn,
	            NULL, /* Ignore truncation in access log */
	            buf,
	            sizeof(buf),
	            "%s - %s [%s] \"%s %s HTTP/%s\" %d %" INT64_FMT " %s %s",
	            src_addr,
	            ri->remote_user == NULL ? "-" : ri->remote_user,
	            date,
	            ri->request_method ? ri->request_method : "-",
	            ri->uri ? ri->uri : "-",
	            ri->http_version,
	            conn->status_code,
	            conn->num_bytes_sent,
	            referer,
	            user_agent);

	if (conn->ctx->callbacks.log_access) {
		conn->ctx->callbacks.log_access(conn, buf);
	}

when I set "callbacks.begin_request" and "callbacks.log_access",I get the "buf" in my function and logout it,  the "conn->status_code" is always "-1". But I can't find the way to modifiy "status_code". I want to set the value.

**Comment by bel2125** [comment]
The status code is currently set automatically for the requests handled internally in civetweb, e.g. for static files, but not for callbacks. There is currently no way to do this in a callback, but that's just a small extension I can do in a few minutes. I think the easiest way is to just return the status code.
Currently you need to return 1 from your callback in order to tell the civetweb the request is handled, and 0 to state it is not handled. The behavior for other values is undefined. So I would define >0 as "request is handled" and store the value in conn->status_code. This is compatible with the present behavior.

**Comment by bel2125** [comment]
Please have a look if the current changes are what you needed.

**Comment by guanglost** [comment]
Thank you for the response! 
Done great!
