### ISSUE TITLE
uri supprt for websockets

### ISSUE THREAD

**Issue by slimshader** [bel2125/civetweb#30]
Will URI/path matching will also be supported for WebSockets?

I mean automatic invocation or registered callback (al'a mg_set_request_handler) for specified URI path when protocol is "ws:". Say mg_set_websocket_connection_handler?

**Comment by bel2125** [comment]
It's been awhile since this issue was opened, but now this interface is available.
It took some time, because I had to restructure the main request handling functions (handle_request, handle_websocket_request) first in order to implement the new function `mg_set_websocket_handler`.

An example how to use it can be found here:
https://github.com/bel2125/civetweb/blob/master/examples/embedded_c/embedded_c.c

**Comment by slimshader** [comment]
Looking nice, no time to check this now though

**Comment by bel2125** [comment]
The code has been tested in the examples.
--> I will close this issue.

Please reopen a new one if you encounter any problem later.
