### ISSUE TITLE
First call to sslize() is very slow

### ISSUE THREAD

**Issue by grunk** [bel2125/civetweb#62]
Hi,
I'm using civetweb embedded in a c++ app. It works great except for the first https request it had to serve which is very slow (up to 10 seconds).
I located the problem in the `sslize()` function , and more precisely on this call : `func(conn->ssl) == 1`.
Unfortunately I don't really understand what this code do, and can't go further alone :(

This how i intiialize civetweb : 

```cpp
const char * options[] = {
	"document_root", DOCUMENT_ROOT, 
	"listening_ports", "80,443s", 
	"ssl_certificate", "D://server.pem", 
	"error_log_file", LOG_FILE,
	0
};
this->m_pServer = new CivetServer(options);
```
I'm using a self signed certificate generated with openssl. I followed the wiki procedure to generate the  certificate.

This delay is only a problem if it occurs on a request. Is there something to initialize before being able to handle request ?

Thanks

**Comment by bel2125** [comment]
`func` is actually a callback function, and could be either `SSL_connect` or `SSL_accept`. 
Do you know which one of these two it is?
Both are actually in the SSL library. Are you using openSSL? What system?

**Comment by grunk** [comment]
I'm using openSSL (1.0.1h) on windows 7 64.
It's the callback to ssl_accept which is slow

**Comment by bel2125** [comment]
I checked the OpenSSL documentation. The first call to SSL_accept may take some time, depending on the ciphers chosen and of course the hardware. For the second call, the session ID is cached, so the call is faster. This is caused by OpenSSL and not specific to civetweb.

If you use civetweb in a process that did already initialize OpenSSL, you may use the `define SSL_ALREADY_INITIALIZED`, as discussed in issue #58 (comments from Jan 6 and Jan 7).

Is there anything more I can do to help you?

**Comment by grunk** [comment]
You can close this issue , thanks for your help.
