### ISSUE TITLE
Can Lua Server Page support  `for`and `if` ?  please see details

### ISSUE THREAD

**Issue by shawnye** [bel2125/civetweb#72]
Can Lua Server Page support  `for` and `if` like this, as `JSTL` do it :
<pre>
&lt;? for i=1,5 do ?&gt;
  &lt;li&gt;&lt;?=i?&gt;&lt;/li&gt;
&lt;? end ?&gt;
</pre>

**Comment by bel2125** [comment]
No. It can not be used this way.
Please have a loot at the example *.lp pages in test directory, e.g.:
  - https://github.com/bel2125/civetweb/blob/master/test/page.lp#L14
  - https://github.com/bel2125/civetweb/blob/master/test/page.lp#L60
  - https://github.com/bel2125/civetweb/blob/master/test/page2.lp#L63

What you want is probably this:

    <? for i=1,5 do 
           mg.write("<li>" .. i "</li>")
       end ?>

**Comment by bel2125** [comment]
Or maybe you prefer this form:

    <? for i=1,5 do mg.write[[
      <li>]]..i..[[</li>
    ]] end ?>

Or you can use directly scripts (*.lua) instead of server pagers (*.lp).
These two files are actually doing the same thing, one in *.lp, the other in *.lua:
  - https://github.com/bel2125/civetweb/blob/master/test/page2.lp
  - https://github.com/bel2125/civetweb/blob/master/test/page2.lua
They are executed in the same way and should return the same result (unless I recently added something to one of them and forgot to do the same in the other one). 
The *.lua scripts look nicer in an editor that supports syntax highlighting for Lua (there are quite some editors that do), since it is all standard Lua syntax. The *.lp pages might look better in an xml editor or an html editor with web preview. My recommendation would be to use *.lp if you have a lot of web contents with just a view lines dynamically generated and *.lua if you have a more sophisticated script - but it's up to you. Both provide the same features for web pages.

I would recommend reading the "Lua Scripts and Lua Server Pages" section in the user manual (https://github.com/bel2125/civetweb/blob/master/docs/UserManual.md).

**Comment by shawnye** [comment]
Thank you !
As I am always struggling with JavaEE programming , I am subject to seperating business logic from view(such as html page) as much as possible, 

I think maybe CiveWeb implementation regard anything in `<? xxxx ?>`  as a lua chunk, if it could compose several  `<? xxxx ?>` s as ONE chunk, I  suggest implemention with TWO `?`s :

<pre>
<?? for i=1,5 do ?>
  <li><?=i?></li>
<? end ??>
</pre>

Is it practicable?

**Comment by bel2125** [comment]
> I think maybe CiveWeb implementation regard anything in `<? xxxx ?>` as a lua chunk

Yes it does.

> I suggest to achieve this feature with TWO ?s :

You mean, this feature should be implemented?

> Is it practicable?

Maybe.
Why do you think this is required?
Basically your `?>` is my `mg.write[[`, 
then your `<?=` is my `]]..`,
then your `?>` is my `..[[`,
and finally your `<?` is my `]]`.
Why is your syntax better for the user?

**Comment by shawnye** [comment]
Yes, none is better:

&lt;? for i=1,5 do mg.write[[
   &lt;tr&gt;
     &lt;td&gt;]]..i..[[&lt;/td&gt;
     &lt;td&gt;&lt;input type="text" name="name_]]..i..[[" &gt;&lt;/td&gt;
     &lt;td&gt;&lt;a href="javascript:void(0)" id="a_id_]]..i..[["&gt;test]]..anchor_i..[[&lt;/a&gt;&lt;/td&gt;
   &lt;/tr&gt;
   ]] ?&gt;

**Comment by bel2125** [comment]
> Yes, none is better.
> If only it could achieve something like simple JSTL does.

Sorry, I did not understand what you mean.

The code below seems to be correct on the first look. Does it not work?

**Comment by shawnye** [comment]
The code above worked, but  does not suite my taste. 
It seems be more clear using JSTL:

&lt;c:forEach begin="1" end="10" var="i"&gt;
&lt;tr&gt;
&lt;td&gt;${i}&lt;/td&gt;
&lt;td&gt;&lt;input type="text" name="name_${i}" &gt;&lt;/td&gt;
&lt;td&gt;&lt;a href="javascript:void(0)" id="a_id_${i}"&gt;test${i}&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;/c:forEach&gt;

Maybe it is about personal taste, so I would like close this topic to save our energy.
