### ISSUE TITLE
non file based PUT requests require authorization

### ISSUE THREAD

**Issue by cdbishop** [bel2125/civetweb#88]
Not sure if this is an issue or if I'm just using the library incorrectly.

I'm using civetweb to implement a RESTful api. I was initially developing against v1.6 and was able to get my project working. However when switching to the master (to take advantage of the changes since v1.6) I found my PUT requests returning 401 Unauthorized.

The cause I have found is the addition of a check for authorization, which is performed before the request is delegated to the handle_request callback. (I haven't defined NO_FILES as I do require supporting of GET requests to return html pages)

Ideally I do not want to implement any authorization for PUT requests as for my purposes I do not wish to force the user to be authorised to use this aspect of the api

I've found the simplest change to resolve this is for put requests to be allowed if no PASSWORD_FILE is found/specified via options, I've tested this change here: https://github.com/cdbishop/civetweb/commit/fe483bfe8dae8dc51a69905fb71ff3e3af646458

However I'm unsure if this change would cause other issue/break functionality for other users?

I guess the first question to ask: Is using civetweb to implement a RESTful api a valid use of the library or is this not the intention of it?

Also It seems based on code comments/function names that the uri is assumed to be pointing to a file (where I require uri end points that don't point to anything, e.g. I have an /api/objects uri which can accept PUT requests) Is this supported? Or am I likely to run into other issues where a file is assumed?

**Comment by cdbishop** [comment]
This behaviour can be seen in the embedded_c example. 
Run up the example.
make a curl request to a path ending in .foo (e.g. curl -X PUT localhost:8888/xy.foo -d 'test')
response is 401 unauthorized.

The same steps performed against the 1.6 release returns 200 ok

Is this intended behaviour?

**Comment by bel2125** [comment]
The `handle_request` function has been completely rewritten, and documented. Before the code was rather complicated and hard to maintain.
The current implementation reflects the behavior I did consider correct.
Probably some special cases work differently now.

With the current code, I can check such situations with a simple look at the comments in `handle_request`, which was one of the main reasons for rewriting the entire function:
You probably use a request handler, added by `mg_set_request_handler`. These handlers are called in step 8 of `handle_request` (currently in this line: https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L6378), after the check if it is a PUT request in step 6 (currently this line: https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L6336).

The new logic is that PUT/DELETE/.. requests to resources handled by scripts do not require a PUT/DELETE authorization, while PUT/DELETE requests to files do.
Callbacks are currently not identified as script resources.
This is not really an intentional decision. For registered callbacks probably `is_script_resource` should be set.

**Comment by bel2125** [comment]
Now all URIs handled by callbacks have the `is_script_resource` set. This should solve the problem.
Could you make a test and tell me if it works for your case?

**Comment by cdbishop** [comment]
Thanks that change resolved my issue
