### ISSUE TITLE
Memory leak when only one handler defined

### ISSUE THREAD

**Issue by mwegithub** [bel2125/civetweb#92]
The **mg_set_request_handler** method does exit the initial loop too early when only one handler is defined and the caller tries to remove that handler. The memory allocated for the handler is thus never freed.

Just started with civetweb on Windows using Visual Studio 2012.
Deleting the CivetServer instance leaks the handler.

**Comment by bel2125** [comment]
The memory leak should be fixed. At least it does not occur in a simple unit test.
Please give me some feedback if it still occurs it your use case.

**Comment by mwegithub** [comment]
I downloaded the last version and retired the test. The handler is not deleted.

In order to track this down, I used the ex_embed_cpp example included in the VC2012 folder. I changed the project settings **General > Use of MFC** to **"Use MFC in a shared library"**. This gives us the debugging and memory checking options of MFC.

In the file **embedded_cpp.cpp** I replaced
```
#include <Windows.h>
```
with
```
#include <afx.h>
```
and added
```
#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif
```
below the line
```
bool exitNow = false;
```

When I now run the sample program and then exit it via 

localhost:8081/exit

MFC dumps all handlers added via addHandler as leads. And this is to be expected because civitweb does not free them, at least not from my understanding of the source code. The example program adds handlers via

*server.addHandler(EXIT_URI, new ExitHandler());*

so the handler has to be freed with delete. But the *mg_set_request_handler_type* function only calls 
```
mg_free(tmp_rh->uri);
mg_free(tmp_rh);
```
but never deletes *tmp_rh.handler*

I doubt that this can work as documented. Or that *mg_set_request_handler_type* can delete handlers at all.

Maybe the caller has to keep the handler pointer around and deletes it after closing the server. That's what I do in my code to avoid the leaks.

**Comment by bel2125** [comment]
Ok. Then I probably looked at the wrong place.
I had a look at the civetweb.c file, not the CivetServer.cpp file ... but this does not contain any `new` operator, and CivetServer.h either ... you mean this line:
https://github.com/bel2125/civetweb/blob/master/examples/embedded_cpp/embedded_cpp.cpp#L114

That's a problem in the sample, not in the server.
At the moment, I do not see a reason why this has to be done with `new ExampleHandler()` anyway, instead of just using a local or global instance of ExampleHandler. Neither ExampleHandler nor CivetHandler has any instance data, just internally some const function pointers to the virtual methods.

My test just tested that civetweb.c does not leak any memory.

**Comment by mwegithub** [comment]
I understand, not a problem for me either.
Maybe you should update the documentation for the addHandler method CivetServer. It currently says:

*@param handler - handler instance to use.
This will be free'ed when the server closes and instances cannot be reused.*

That's what mislead me and caused this. Thanks for your support (and for maintaining civetweb!).
